# Generated by Django 3.1.7 on 2021-04-27 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='paises',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=120)),
                ('nombre', models.CharField(max_length=120)),
                ('abreviatura', models.CharField(max_length=60)),
                ('estado', models.BooleanField()),
                ('fecha_creacion', models.DateTimeField()),
                ('fecha_modificacion', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ciudades',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=120)),
                ('nombre', models.CharField(max_length=120)),
                ('abreviatura', models.CharField(max_length=60)),
                ('estado', models.BooleanField()),
                ('fecha_creacion', models.DateTimeField()),
                ('fecha_modificacion', models.DateTimeField()),
                ('id_pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='affiliate.paises')),
            ],
        ),
        migrations.CreateModel(
            name='afiliados',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=160)),
                ('apellidos', models.CharField(max_length=160)),
                ('numero_movil', models.IntegerField()),
                ('direccion', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('estado', models.BooleanField()),
                ('fecha_creacion', models.DateTimeField()),
                ('fecha_modificacion', models.DateTimeField()),
                ('id_ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='affiliate.ciudades')),
            ],
        ),
    ]
